apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sahal-test-app-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/Ahmedkayd/test-application.git'
        revision: main
        directories:
          - path: k8s
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: sahaluniv
      source:
        repoURL: 'https://github.com/Ahmedkayd/test-application.git'
        targetRevision: main
        path: k8s
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: sahaluniv
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
